newmarcel/KeepingYouAwake

- README.md
This adds the information about an installation via caskroom.io
> Installation via cask

- KeepingYouAwake/Base.lproj/MainMenu.xib
- KeepingYouAwake/KYAAppController.m
I wrote up some code to allow for setting the default duration.  Set by holding down option in the duration list
> Ability to set default duration

- CHANGELOG.md
- Credits.rtf
- KeepingYouAwake.xcodeproj/project.pbxproj
- KeepingYouAwake/fr.lproj/InfoPlist.strings
- KeepingYouAwake/fr.lproj/Localizable.strings
- KeepingYouAwake/fr.lproj/MainMenu.strings
- KeepingYouAwake/fr.lproj/Preferences.strings
This is the cleaned up version of #51 for merging.
> Translation into French [Cleaned Up]

- Credits.rtf
- KeepingYouAwake.xcodeproj/project.pbxproj
- KeepingYouAwake/ko.lproj/InfoPlist.strings
- KeepingYouAwake/ko.lproj/Localizable.strings
- KeepingYouAwake/ko.lproj/MainMenu.strings
- KeepingYouAwake/ko.lproj/Preferences.strings
- Localizations/KeepingYouAwake/ko.xliff
I translated this app into Korean.
> Translation into Korean

- Credits.rtf
- Localizations/KeepingYouAwake/es.xliff
It wasn't very clear on the localizations readme but I hope the xliff file is enough to import into Xcode
> Spanish translation

- Credits.rtf
Danish translation credits added.
> Update Credits.rtf - Danish translation

- Credits.rtf
- KeepingYouAwake.xcodeproj/project.xcworkspace/xcshareddata/KeepingYouAwake.xcscmblueprint
- Localizations/KeepingYouAwake/tr.xliff
> Turkish language support

- KeepingYouAwake/KYAAppController.m
- KeepingYouAwake/StatusItemController/KYAStatusItemController.h
- KeepingYouAwake/StatusItemController/KYAStatusItemController.m
[How to use]
open keepingyouawake:///toggle
> Added toggle function to custom url action.

- LICENSE
This way it can be automaintained each year
> Update LICENSE from 2020 to 'present'

- KeepingYouAwake/Extensions/NSUserDefaults+Keys.h
- KeepingYouAwake/Extensions/NSUserDefaults+Keys.m
- KeepingYouAwake/KYASleepWakeTimer/KYASleepWakeTimer.m
- KeepingYouAwake/Preferences/Advanced/KYAAdvancedPreferencesViewController.m
Here's my attempt to add display sleep support.
I am not experienced in this at all, so apologies if there are obvious mistakes.
Basically I've tried to implement a preference that uses caffeinate with the '-i' argument to allow display sleep while keeping the machine awake.
thanks, hope this helps.
Tristan.
#138 #115 #25 #12
> Add display sleep support

- CHANGELOG.md
- Configuration.xcconfig
- KYALauncher/MainMenu.xib
- KeepingYouAwake/Base.lproj/MainMenu.xib
- KeepingYouAwake/Preferences/Base.lproj/Preferences.storyboard
- KeepingYouAwake/Preferences/KYAPreferencesWindowController.m
- KeepingYouAwake/StatusItemController/KYAStatusItemController.m
- README.md
Raised the minimum deployment target to macOS Sierra. Goodbye Yosemite and El Capitan!
> Raised Deployment Target to macOS Sierra

- CHANGELOG.md
- Credits.rtf
- KeepingYouAwake.xcodeproj/project.pbxproj
- KeepingYouAwake/Preferences/ru.lproj/Preferences.strings
- KeepingYouAwake/ru.lproj/InfoPlist.strings
- KeepingYouAwake/ru.lproj/Localizable.strings
- KeepingYouAwake/ru.lproj/MainMenu.strings
- Localizations/KeepingYouAwake/ru.xcloc/Localized Contents/ru.xliff
- Localizations/KeepingYouAwake/ru.xcloc/contents.json
- Localizations/l10n-config.sh
- docs/Versions/v1.6.0pre.md
Integrated the Russian translation from https://github.com/newmarcel/KeepingYouAwake/issues/147 and https://github.com/newmarcel/KeepingYouAwake/issues/143.
> Russian Translation

- CHANGELOG.md
- KeepingYouAwake/Preferences/fr.lproj/Preferences.strings
- KeepingYouAwake/fr.lproj/Localizable.strings
- Localizations/KeepingYouAwake/fr.xcloc/Localized Contents/fr.xliff
- Localizations/KeepingYouAwake/fr.xcloc/contents.json
> Integrated French Translation Updates

- Localizations/KeepingYouAwake/da.xcloc/Localized Contents/da.xliff
New translations added and minor improvements of existing translations.
> Added missing localisations in da.xliff

- Credits.rtf
- KYAKit/uk.lproj/Localizable.strings
- KeepingYouAwake.xcodeproj/project.pbxproj
- KeepingYouAwake/Preferences/KYAAdvancedPreferencesViewController/uk.lproj/KYAAdvancedPreferencesViewController.strings
- KeepingYouAwake/Preferences/KYADurationPreferencesViewController/uk.lproj/KYAAddDurationPreferencesViewController.strings
- KeepingYouAwake/Preferences/KYADurationPreferencesViewController/uk.lproj/KYADurationPreferencesViewController.strings
- KeepingYouAwake/Preferences/KYAGeneralPreferencesViewController/uk.lproj/KYAGeneralPreferencesViewController.strings
- KeepingYouAwake/Preferences/KYAUpdatePreferencesViewController/uk.lproj/KYAUpdatePreferencesViewController.strings
- KeepingYouAwake/Preferences/uk.lproj/KYAPreferences.strings
- KeepingYouAwake/uk.lproj/InfoPlist.strings
- KeepingYouAwake/uk.lproj/Localizable.strings
- KeepingYouAwake/uk.lproj/MainMenu.strings
Hi
One more language on board :) Thanks for this awesome utility!
> Add Localisation: Ukrainian

- KeepingYouAwake/Preferences/KYAAdvancedPreferencesViewController/ja.lproj/KYAAdvancedPreferencesViewController.strings
- KeepingYouAwake/Preferences/KYADurationPreferencesViewController/ja.lproj/KYAAddDurationPreferencesViewController.strings
- KeepingYouAwake/Preferences/KYADurationPreferencesViewController/ja.lproj/KYADurationPreferencesViewController.strings
- KeepingYouAwake/Preferences/KYAGeneralPreferencesViewController/ja.lproj/KYAGeneralPreferencesViewController.strings
- KeepingYouAwake/Preferences/KYAUpdatePreferencesViewController/ja.lproj/KYAUpdatePreferencesViewController.strings
- KeepingYouAwake/Preferences/ja.lproj/KYAPreferences.strings
- KeepingYouAwake/ja.lproj/InfoPlist.strings
- KeepingYouAwake/ja.lproj/Localizable.strings
- Localizations/KeepingYouAwake/ja.xcloc/Localized Contents/ja.xliff
- Localizations/KeepingYouAwake/ja.xcloc/contents.json
I wrote Japanese text for the app. Please merge this if nothing problem.
> Support Japanese language

- Credits.rtf
- KeepingYouAwake/Preferences/KYAAdvancedPreferencesViewController/tr.lproj/KYAAdvancedPreferencesViewController.strings
- KeepingYouAwake/Preferences/KYADurationPreferencesViewController/tr.lproj/KYAAddDurationPreferencesViewController.strings
- KeepingYouAwake/Preferences/KYADurationPreferencesViewController/tr.lproj/KYADurationPreferencesViewController.strings
- KeepingYouAwake/Preferences/KYAGeneralPreferencesViewController/tr.lproj/KYAGeneralPreferencesViewController.strings
- KeepingYouAwake/Preferences/KYAUpdatePreferencesViewController/tr.lproj/KYAUpdatePreferencesViewController.strings
- KeepingYouAwake/Preferences/tr.lproj/KYAPreferences.strings
- KeepingYouAwake/tr.lproj/InfoPlist.strings
- KeepingYouAwake/tr.lproj/Localizable.strings
- Localizations/KeepingYouAwake/tr.xcloc/Localized Contents/tr.xliff
Translations and improvements for Turkish localisation.
> Turkish localisation

- KeepingYouAwake/KYAAppController/KYAAppController.m
- KeepingYouAwake/KYALocalizedStrings.m
- KeepingYouAwake/Preferences/KYAAdvancedPreferencesViewController/KYAAdvancedPreferencesViewController.m
- Packages/KYAApplicationSupport/Sources/KYAApplicationSupport/NSUserDefaults+Keys.m
- Packages/KYAApplicationSupport/Sources/KYAApplicationSupport/include/KYAApplicationSupport/NSUserDefaults+Keys.h
Addresses https://github.com/newmarcel/KeepingYouAwake/issues/84
> Keep the mac from going to sleep when connected to an external monitor

- Localizations/KeepingYouAwake/fr.xcloc/Localized Contents/fr.xliff
Hi @newmarcel ,
Thanks for your work on the app!
I updated the French translations with missing terms and some more idiomatic expressions.
> Adding missing French translations

- CHANGELOG.md
- Configuration.xcconfig
- Credits.rtf
- KeepingYouAwake.xcodeproj/project.pbxproj
- KeepingYouAwake/Localizable.xcstrings
- KeepingYouAwake/Settings/KYAAdvancedSettingsViewController/Base.lproj/KYAAdvancedSettingsViewController.xib
- KeepingYouAwake/Settings/KYAAdvancedSettingsViewController/mul.lproj/KYAAdvancedSettingsViewController.xcstrings
- KeepingYouAwake/Settings/KYABatterySettingsViewController/mul.lproj/KYABatterySettingsViewController.xcstrings
- KeepingYouAwake/Settings/KYADurationSettingsViewController/mul.lproj/KYAAddDurationViewController.xcstrings
- KeepingYouAwake/Settings/KYADurationSettingsViewController/mul.lproj/KYADurationSettingsViewController.xcstrings
- KeepingYouAwake/Settings/KYAGeneralSettingsViewController/mul.lproj/KYAGeneralSettingsViewController.xcstrings
- KeepingYouAwake/Settings/KYASettings.xcstrings
- KeepingYouAwake/Settings/KYAUpdateSettingsViewController/mul.lproj/KYAUpdateSettingsViewController.xcstrings
- Localizations/KeepingYouAwake/sk.xcloc/Localized Contents/sk.xliff
- Localizations/KeepingYouAwake/sk.xcloc/contents.json
- Localizations/l10n-config.sh
Added a Slovak localization.
An attached preview build can be used for verification purposes.
[KeepingYouAwake-1.6.6sk3.zip](https://github.com/newmarcel/KeepingYouAwake/files/13800903/KeepingYouAwake-1.6.6sk3.zip)
> Added a Slovak Localization

- KeepingYouAwake/Localizable.xcstrings
- KeepingYouAwake/Settings/KYAAdvancedSettingsViewController/mul.lproj/KYAAdvancedSettingsViewController.xcstrings
- KeepingYouAwake/Settings/KYABatterySettingsViewController/mul.lproj/KYABatterySettingsViewController.xcstrings
- KeepingYouAwake/Settings/KYADurationSettingsViewController/mul.lproj/KYAAddDurationViewController.xcstrings
- KeepingYouAwake/Settings/KYADurationSettingsViewController/mul.lproj/KYADurationSettingsViewController.xcstrings
- KeepingYouAwake/Settings/KYAGeneralSettingsViewController/mul.lproj/KYAGeneralSettingsViewController.xcstrings
- KeepingYouAwake/Settings/KYASettings.xcstrings
Hi @newmarcel.
Thanks for your kind work.
I've updated the missing Chinese(zh) translations.
> Update missing Chinese localization.

- KeepingYouAwake/Localizable.xcstrings
- KeepingYouAwake/Settings/KYAAdvancedSettingsViewController/mul.lproj/KYAAdvancedSettingsViewController.xcstrings
- KeepingYouAwake/Settings/KYABatterySettingsViewController/mul.lproj/KYABatterySettingsViewController.xcstrings
- KeepingYouAwake/Settings/KYADurationSettingsViewController/mul.lproj/KYADurationSettingsViewController.xcstrings
- KeepingYouAwake/Settings/KYASettings.xcstrings
Hi! Since our beloved app has grown and got some new features – it's time to let it shine with the proper translations.
- updated and added missing Ukrainian localisation
> Updated Ukrainian localisation

- Localizations/KeepingYouAwake/ru.xcloc/Localized Contents/ru.xliff
Updated the Russian translation to be more full and accurate.
Instead of Xcode I used the app called [Loca Studio](https://apps.apple.com/us/app/loca-studio/id1465684707) to actually translate the `ru.xliff` file directly. It is the most convenient way I found. But for some reason it didn't add `state="translated"` parameter to the <target> tag for the newly added ones. So I've added them manually. 
There are a couple of strings that I haven't actually found in the app itself while using it. But I translated them nonetheless. 
Hope this translate would be useful to you and won't break anything :) 
Thanks for a great app!
> Update of Russian language localisation

- Localizations/KeepingYouAwake/hi.xcloc/Localized Contents/hi.xliff
- Localizations/KeepingYouAwake/hi.xcloc/contents.json
This commit introduces new localization files for the Hindi language, including the contents.json and XLIFF files, ensuring that the app is accessible to Hindi-speaking users.
> Add Hindi localization files for KeepingYouAwake

- .gitignore
- Localizations/KeepingYouAwake/el.xcloc/Localized Contents/el.xliff
- Localizations/KeepingYouAwake/el.xcloc/contents.json
- Localizations/KeepingYouAwake/fi.xcloc/Localized Contents/fi.xliff
- Localizations/KeepingYouAwake/fi.xcloc/contents.json
This was my first localizations try through github after a million years when we just emailed .proj s to the app author :)
it really took me some time to realize how works "a repository".
> Added Greek and Finnish localizations
